site_name: Linux and Virtualization
nav:
- Home: index.md
- About: about.md
- Guides:
  - Getting Started:
    - Connecting to Servers: guides/wiring/connecting.md
    - Assigning IPs: guides/assigning.md
  - Connecting to VMs:
    - Connecting to ESXI: guides/connecting/VMWare.md
    - Finding NAS: guides/raidar.md
    - Connecting to NAS: guides/connecting/NAS.md
  - Configuration:
    - Configuring ESXI: guides/configuration/ESXI.md
    - Configuring the NAS: guides/configuration/con_NAS.md
    - Configuring Shared Storage: guides/configuration/NASPool.md
  - Setting Up:
    - Configure ISCSI: guides/setup/ISCSI.md
    - Configure VMs: guides/setup/newVM.md
theme: readthedocs
